# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 02:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memory_trunk_app', '0002_profile_users_followed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_public', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('happy_factor', models.PositiveIntegerField()),
                ('sad_factor', models.PositiveIntegerField()),
                ('likes', models.ManyToManyField(related_name='memory_likes', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
