# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('memory_trunk_app', '0004_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tip',
            name='do',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tip',
            name='is_public',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tip',
            name='likes',
            field=models.ManyToManyField(related_name='tip_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='memories',
            field=models.ManyToManyField(to='memory_trunk_app.Memory'),
        ),
        migrations.AddField(
            model_name='tip',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='tip',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tip',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
