# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memory_trunk_app', '0005_auto_20170316_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('is_public', models.IntegerField(default=1)),
                ('content', models.TextField(default='')),
                ('likes', models.ManyToManyField(related_name='perspective_likes', to=settings.AUTH_USER_MODEL)),
                ('memories', models.ManyToManyField(to='memory_trunk_app.Memory')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
