# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_trunk_app', '0007_auto_20170317_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspective',
            name='is_public',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tip',
            name='is_public',
            field=models.BooleanField(default=1),
        ),
    ]
