# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_trunk_app', '0009_auto_20170318_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='do',
            field=models.BooleanField(default=1),
        ),
    ]
