# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_trunk_app', '0011_auto_20170322_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='happy_factor',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
