# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_trunk_app', '0012_auto_20170322_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='do',
        ),
    ]
